---
title: "How does the Bootstrap method work?"
author: "Bhawna G. Panwar"
date: '2017-06-11'
description: ''
featured: ''
featuredalt: ''
featuredpath: ''
linktitle: ''
slug: first-blog-rmd
tags: []
categories: []
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question of the day?

Suppose we have a normal population with a mean  of 3 and a standard deviation of 1, how would we illustrate the bootstrap method here?


```{r}
set.seed(1)
srs <- rnorm(25, mean=3)
resamps <- replicate(1000, sample(srs, 25, TRUE), simplify = FALSE)
x_bar_star <- sapply(resamps, mean, simplify =TRUE)

```

Let's create a histogram here and fit normal curve.
```{r}
hist(x_bar_star, breaks = 40, prob = TRUE)
curve(dnorm(x, 3, 0.2), add = TRUE) 
```

We can calculate the difference now.
```{r}
mean(x_bar_star)
mean(srs)
mean(x_bar_star) - mean(srs)
```
Now we observe the standard error of the me x_bar_star with the sample standard deviation of the resample statistics.

```{r}
sd(x_bar_star)

```