---
title: Statistical Analysis-Examples
author: Bhawna G. Panwar
date: '2017-07-02'
slug: statistical-analysis-examples
categories: []
tags: []
description: ''
featured: ''
featuredalt: ''
featuredpath: ''
linktitle: ''
---
Statistical Analysis consists of code from the Chapter Lab Sections 4.6.1 and 4.6.2(Induction to Statitical book)
```{r}
library (ISLR)
names(Smarket )
```
```{r}
dim(Smarket )
```

```{r}
summary (Smarket )
```

```{r}
pairs(Smarket )
```
```{r}
#cor(Smarket )
```

```{r}
cor(Smarket [,-9])
```

```{r}
attach (Smarket )
plot(Volume )
```

Following code runs the logististic Regression labcode 4.6.2
```{r}
glm.fit=glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume ,data=Smarket ,family =binomial )
summary (glm.fit )
```

```{r}
coef(glm.fit)
```

```{r}
summary (glm.fit )$coef
```

```{r}
summary (glm.fit )$coef [,4]
```

```{r}
glm.probs =predict(glm.fit,type ="response")
glm.probs [1:10]
```
```{r}
contrasts (Direction )
```

```{r}
glm.pred=rep ("Down " ,1250)
glm.pred[glm.probs >.5]=" Up"
```

```{r}
table(glm.pred ,Direction )
```
```{r}
(507+145) /1250
```

```{r}
mean(glm.pred==Direction )
```
```{r}
train =(Year <2005)
Smarket.2005= Smarket [! train ,]
dim(Smarket.2005)
Direction.2005= Direction [! train]
```

```{r}
glm.fit=glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume ,
data=Smarket,family =binomial ,subset =train )
glm.probs =predict (glm.fit ,Smarket.2005 , type="response")
```

```{r}
glm.pred=rep ("Down " ,252)
glm.pred[glm.probs >.5]=" Up"
table(glm.pred ,Direction.2005)
```

```{r}
mean(glm.pred== Direction.2005)
```

```{r}
mean(glm.pred!= Direction.2005)
```

```{r}
glm.fit=glm(Direction~Lag1+Lag2 ,data=Smarket ,family =binomial ,
subset =train)
glm.probs =predict (glm.fit ,Smarket.2005,type="response")
glm.pred=rep ("Down " ,252)
glm.pred[glm.probs >.5]="Up"
table(glm.pred ,Direction.2005)
```
```{r}
mean(glm.pred== Direction.2005)
```

```{r}
106/(106+76)
```

```{r}
predict (glm.fit, newdata =data.frame(Lag1=c(1.2 ,1.5),Lag2=c(1.1 , -0.8) ),type ="response")
```
Reference: An Introduction to Statistical Learning with Applications in R
Authors: James, G., Witten, D., Hastie, T., Tibshirani, R. 